"""The analytics store: declarative base, engine and sessions.

This is the second database in the repository and it is deliberately separate
from ``app/web/db/base.py``:

* ``Base`` (Postgres) holds platform tables - organizations, users, watchlists.
* ``AnalyticsBase`` (SQLite, this module) holds every **derived** analytical
  result - metrics, factor scores, valuations, forecasts, backtests, job state
  and the model registry.

Raw market observations live in neither. They stay in the scraper's database
and are read through ``MarketDataSource``; the engines here compute from them
and write only their own results. The file is migrated by its own Alembic chain
(``alembic -n analytics``) so a schema change never touches the platform chain.

Sync only. The engines are batch computations run from the CLI, cron and
Celery; nothing here is awaited inside a request.

    codegraph explore "AnalyticsBase get_analytics_engine analytics_session"
"""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager
from functools import lru_cache
from pathlib import Path
from typing import Any

from sqlalchemy import MetaData, create_engine, event
from sqlalchemy.engine import Engine
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from app.web.config import Settings

# Same convention as the platform base so constraint names are stable and
# reviewable in autogenerated migrations.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class AnalyticsBase(DeclarativeBase):
    """Declarative base for every table in the analytics store."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


#: How long a connection waits for the writer lock before giving up.
BUSY_TIMEOUT_SECONDS = 120


def analytics_url(db_path: Path) -> str:
    """SQLAlchemy URL for the analytics SQLite file."""
    return f"sqlite+pysqlite:///{db_path}"


def _apply_pragmas(dbapi_connection: Any, _record: Any) -> None:
    # WAL lets the API read while a job writes and survives an unclean exit far
    # better than the rollback journal. Foreign keys are off by default in
    # SQLite; every child table here relies on them.
    cursor = dbapi_connection.cursor()
    cursor.execute("PRAGMA journal_mode=WAL")
    cursor.execute("PRAGMA foreign_keys=ON")
    cursor.execute(f"PRAGMA busy_timeout={BUSY_TIMEOUT_SECONDS * 1000}")
    cursor.close()


def build_analytics_engine(db_path: Path) -> Engine:
    """A fresh engine for ``db_path``; the parent directory is created."""
    db_path.parent.mkdir(parents=True, exist_ok=True)
    # A job can hold the single SQLite writer for minutes; a CLI command started
    # meanwhile waits instead of failing with "database is locked".
    engine = create_engine(
        analytics_url(db_path), future=True, connect_args={"timeout": BUSY_TIMEOUT_SECONDS}
    )
    event.listen(engine, "connect", _apply_pragmas)
    return engine


@lru_cache(maxsize=8)
def _engine_for(db_path: str) -> Engine:
    return build_analytics_engine(Path(db_path))


def get_analytics_engine(settings: Settings) -> Engine:
    """The process-wide engine for the configured analytics file (cached per path)."""
    return _engine_for(str(settings.analytics_db_path))


def get_analytics_session_factory(settings: Settings) -> sessionmaker[Session]:
    return sessionmaker(bind=get_analytics_engine(settings), expire_on_commit=False)


@contextmanager
def analytics_session(settings: Settings) -> Iterator[Session]:
    """Context-managed session: commits on success, rolls back on any exception."""
    session = get_analytics_session_factory(settings)()
    try:
        yield session
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()


__all__ = [
    "AnalyticsBase",
    "analytics_session",
    "analytics_url",
    "build_analytics_engine",
    "get_analytics_engine",
    "get_analytics_session_factory",
]
