"""Declarative base, engines, and session factories.

Two engines live here and they are not interchangeable:

* the **async** engine backs every request path (``get_async_session``);
* the **sync** engine exists for Alembic and Celery tasks only.

Importing the sync engine into a router is a bug — it blocks the event loop.

    codegraph explore "get_async_session get_sync_session Base metadata"
"""

from __future__ import annotations

from collections.abc import AsyncGenerator, Generator
from typing import Any

from sqlalchemy import MetaData, create_engine
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from app.web.config import Settings, get_settings

# Explicit naming convention so autogenerated migrations produce stable,
# reviewable constraint names instead of backend-generated ones.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every model in this repo."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def build_async_engine(settings: Settings) -> AsyncEngine:
    """Create the asyncpg engine used by the API."""
    return create_async_engine(
        settings.database_url,
        echo=settings.db_echo,
        pool_size=settings.db_pool_size,
        max_overflow=settings.db_max_overflow,
        pool_pre_ping=True,
        future=True,
    )


def build_async_session_factory(engine: AsyncEngine) -> async_sessionmaker[AsyncSession]:
    """Session factory bound to the async engine."""
    return async_sessionmaker(
        bind=engine,
        class_=AsyncSession,
        expire_on_commit=False,
        autoflush=False,
    )


async def get_async_session() -> AsyncGenerator[AsyncSession, None]:
    """FastAPI dependency yielding a request-scoped ``AsyncSession``.

    Commits on success, rolls back on any exception, always closes.
    """
    from app.web.core.dependencies import get_app_state

    session_factory = get_app_state().session_factory
    async with session_factory() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise


# ---------------------------------------------------------------------------
# Sync engine — Alembic and Celery ONLY
# ---------------------------------------------------------------------------
_sync_engine: Any = None
_sync_session_factory: sessionmaker[Session] | None = None


def get_sync_session_factory() -> sessionmaker[Session]:
    """Lazily built blocking session factory for Alembic and Celery tasks."""
    global _sync_engine, _sync_session_factory
    if _sync_session_factory is None:
        settings = get_settings()
        _sync_engine = create_engine(
            settings.sync_database_url,
            echo=settings.db_echo,
            pool_pre_ping=True,
            future=True,
        )
        _sync_session_factory = sessionmaker(bind=_sync_engine, expire_on_commit=False)
    return _sync_session_factory


def get_sync_session() -> Generator[Session, None, None]:
    """Context-managed blocking session for Celery task bodies."""
    factory = get_sync_session_factory()
    session = factory()
    try:
        yield session
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()
