"""initial schema

Revision ID: 755611cd9329
Revises:
Create Date: 2026-09-06 14:49:43.436568+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "755611cd9329"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Named PostgreSQL ENUM types created by this migration. Kept in one place so
#: downgrade() can drop every one of them.
ENUM_TYPES: tuple[str, ...] = (
    "connector_status",
    "connector_type",
    "instrument_status",
    "onboarding_status",
    "organization_status",
    "report_kind",
    "report_run_status",
    "user_role",
    "user_status",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instruments",
        sa.Column("ticker_symbol", sa.String(length=24), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("sector", sa.String(length=120), nullable=True),
        sa.Column("exchange", sa.String(length=16), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "suspended", "delisted", name="instrument_status"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instruments")),
    )
    op.create_index(op.f("ix_instruments_is_active"), "instruments", ["is_active"], unique=False)
    op.create_index(op.f("ix_instruments_sector"), "instruments", ["sector"], unique=False)
    op.create_index(
        op.f("ix_instruments_ticker_symbol"), "instruments", ["ticker_symbol"], unique=True
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "active", "suspended", name="organization_status"),
            nullable=False,
        ),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True)
    op.create_table(
        "connectors",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "connector_type",
            sa.Enum("supabase", "scraper", "csv_archive", name="connector_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("unconfigured", "connected", "error", name="connector_status"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("credential_ref", sa.String(length=255), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_connectors_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connectors")),
    )
    op.create_index(
        op.f("ix_connectors_organization_id"), "connectors", ["organization_id"], unique=False
    )
    op.create_table(
        "indicator_snapshots",
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("close_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("price_change_1d_pct", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("price_change_1w_pct", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("price_change_1m_pct", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("rsi_14", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("moving_average_20d", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("moving_average_50d", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("moving_average_200d", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_indicator_snapshots_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_indicator_snapshots")),
        sa.UniqueConstraint("instrument_id", "as_of_date", name="uq_indicator_snapshot"),
    )
    op.create_index(
        op.f("ix_indicator_snapshots_as_of_date"),
        "indicator_snapshots",
        ["as_of_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_indicator_snapshots_instrument_id"),
        "indicator_snapshots",
        ["instrument_id"],
        unique=False,
    )
    op.create_table(
        "onboarding_state",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("current_step", sa.Integer(), nullable=False),
        sa.Column("completed_steps", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column("skipped_steps", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "not_started", "in_progress", "completed", "abandoned", name="onboarding_status"
            ),
            nullable=False,
        ),
        sa.Column("step_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_completed_step_name", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "current_step >= 1 AND current_step <= 7",
            name=op.f("ck_onboarding_state_current_step_in_range"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_onboarding_state_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_onboarding_state")),
    )
    op.create_index(
        op.f("ix_onboarding_state_organization_id"),
        "onboarding_state",
        ["organization_id"],
        unique=True,
    )
    op.create_table(
        "price_bars",
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("bar_date", sa.Date(), nullable=False),
        sa.Column("open_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("high_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("low_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("close_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("adjusted_close", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("previous_close", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_price_bars_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_bars")),
        sa.UniqueConstraint("instrument_id", "bar_date", name="uq_price_bar_instrument_date"),
    )
    op.create_index(op.f("ix_price_bars_bar_date"), "price_bars", ["bar_date"], unique=False)
    op.create_index(
        op.f("ix_price_bars_instrument_id"), "price_bars", ["instrument_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "platform_admin",
                "org_admin",
                "analyst",
                "portfolio_manager",
                "trader",
                "research_viewer",
                "client",
                name="user_role",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending_verification", "active", "disabled", name="user_status"),
            nullable=False,
        ),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_users_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "report_runs",
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("requested_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "kind", sa.Enum("daily", "weekly", "monthly", name="report_kind"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "succeeded", "failed", name="report_run_status"),
            nullable=False,
        ),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("output_path", sa.String(length=512), nullable=True),
        sa.Column("triggered_by", sa.String(length=32), nullable=False),
        sa.Column("instruments_analyzed", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_report_runs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_report_runs_requested_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_runs")),
    )
    op.create_index(op.f("ix_report_runs_kind"), "report_runs", ["kind"], unique=False)
    op.create_index(
        op.f("ix_report_runs_organization_id"), "report_runs", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_report_runs_status"), "report_runs", ["status"], unique=False)
    op.create_table(
        "watchlists",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_watchlists_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_watchlists_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlists")),
        sa.UniqueConstraint("organization_id", "name", name="uq_watchlist_org_name"),
    )
    op.create_index(
        op.f("ix_watchlists_organization_id"), "watchlists", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_watchlists_owner_user_id"), "watchlists", ["owner_user_id"], unique=False
    )
    op.create_table(
        "watchlist_items",
        sa.Column("watchlist_id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_watchlist_items_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlists.id"],
            name=op.f("fk_watchlist_items_watchlist_id_watchlists"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist_items")),
        sa.UniqueConstraint("watchlist_id", "instrument_id", name="uq_watchlist_item"),
    )
    op.create_index(
        op.f("ix_watchlist_items_instrument_id"), "watchlist_items", ["instrument_id"], unique=False
    )
    op.create_index(
        op.f("ix_watchlist_items_watchlist_id"), "watchlist_items", ["watchlist_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_watchlist_items_watchlist_id"), table_name="watchlist_items")
    op.drop_index(op.f("ix_watchlist_items_instrument_id"), table_name="watchlist_items")
    op.drop_table("watchlist_items")
    op.drop_index(op.f("ix_watchlists_owner_user_id"), table_name="watchlists")
    op.drop_index(op.f("ix_watchlists_organization_id"), table_name="watchlists")
    op.drop_table("watchlists")
    op.drop_index(op.f("ix_report_runs_status"), table_name="report_runs")
    op.drop_index(op.f("ix_report_runs_organization_id"), table_name="report_runs")
    op.drop_index(op.f("ix_report_runs_kind"), table_name="report_runs")
    op.drop_table("report_runs")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_price_bars_instrument_id"), table_name="price_bars")
    op.drop_index(op.f("ix_price_bars_bar_date"), table_name="price_bars")
    op.drop_table("price_bars")
    op.drop_index(op.f("ix_onboarding_state_organization_id"), table_name="onboarding_state")
    op.drop_table("onboarding_state")
    op.drop_index(op.f("ix_indicator_snapshots_instrument_id"), table_name="indicator_snapshots")
    op.drop_index(op.f("ix_indicator_snapshots_as_of_date"), table_name="indicator_snapshots")
    op.drop_table("indicator_snapshots")
    op.drop_index(op.f("ix_connectors_organization_id"), table_name="connectors")
    op.drop_table("connectors")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_instruments_ticker_symbol"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_sector"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_is_active"), table_name="instruments")
    op.drop_table("instruments")
    # PostgreSQL keeps named ENUM types after their tables are dropped, so
    # downgrade must remove them explicitly. Without this, re-running
    # `upgrade head` fails with "type <name> already exists".
    for enum_name in ENUM_TYPES:
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
    # ### end Alembic commands ###
